### ISSUE TITLE
[Research] Content Complexity Categorization

### ISSUE THREAD

**Issue by hborawski** [player-ui/tools#161]
### Description
For products that enforce rendering budgets, or SLAs for rendering time we need a way to quantify the complexity of content, and assign it a weighted value to represent its cost on the user device.

Explore static analysis approaches for Player content for categorizing based on complexity. 

### Outcome
This research task should create a new enhancement issue for final implementation, with guidance on approach from this research.

**Comment by KetanReddy** [comment]
Basic example started in [this branch](https://github.com/player-ui/tools/tree/feature/measure-content-complexity) with a couple to-dos

- [ ] Get nested bindings/expressions working. Right now since we stop processing them after they are first detected they never fall through to finish the rest of the processing. I mocked out the basic interface for the model/expression evaluator so that might need to get fleshed out a bit more to do more parsing without having to do processing. 
- [ ] Identify and weight nodes with `Template` functionality. Templates are a runtime hit for Player to expand the template so we should increase the weight of any nodes within a template (and increase that weight for compound templates) but for that we'll need to be able to determine if any node is the child of a template node which is something we currently can't do as part of the LSP. This is something we'll need to do though in general as we expand validation functionality (related #91 )
- [ ] Determine more accurate weighting of node types

**Comment by KetanReddy** [comment]
Made #162 to track next steps
