### ISSUE TITLE
Applicability does not accept a binding

### ISSUE THREAD

**Issue by A1shK** [player-ui/tools#179]
**Describe the bug**

Often times, when setting a component's applicability we might use a binding. However, right now setting a binding (ex: `applicability={show}`) as applicability in DSL always results in a truthy value due to [this](https://github.com/player-ui/tools/blob/main/language/dsl/src/components.tsx#L114) casting. As a way around this, we have to wrap this binding in an expression to make it work `applicability={e`${show} `}`. 

**To Reproduce**

To reproduce this issue, you can use [this gist](https://gist.github.com/A1shK/dfaeab5f6491ca4a2c474f7292c06f54) in the storybook. There are two strings in a collection - both of them should not be showing up since we are using the binding `show` to set the applicability and it is `false`. The difference between the first and the second Text is that in the first one, we are just using `show` as a binding. Whereas, in the second one we are wrapping it in an expression. 
<img width="300" alt="image" src="https://github.com/user-attachments/assets/817750d7-b920-4b4b-a526-1c2cd05c4f13">

**Expected behavior**

The first Text in the collection should also be hidden

**Screenshots**

| Current result| Expected result (an empty screen 😅) |
| --|--|
|<img width="353" alt="image" src="https://github.com/user-attachments/assets/0d933e1f-d3c6-4b88-832d-ddb14f6556b7"> |<img width="377" alt="image" src="https://github.com/user-attachments/assets/04a394c8-0f4a-47da-b9b9-43f9833e655d">|

**Environment:**

**Additional context**

**Comment by KetanReddy** [comment]
Interesting 🤔. It looks like when we handle applicability [here](https://github.com/player-ui/tools/blob/main/language/dsl/src/components.tsx#L110-L116) we just do a basic check to see if `applicability` is a boolean, otherwise we call the `.toValue()` method of the template. Since `applicability` is assumed to be an expression it makes sense why an expression is fine but when using a binding, the template syntax should be used so Player resolves the binding from  the model to evaluate if its truthy or not. 

_Should_ be an easy fix
